package org.joey.pojo;

import com.alibaba.excel.annotation.ExcelProperty;

import java.math.BigDecimal;

public class Grade {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.math_total
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    @ExcelProperty("数学总分")
    private BigDecimal mathTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.Java_total
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    @ExcelProperty("Java总分")
    private BigDecimal javaTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.english_total
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    @ExcelProperty("英语总分")
    private BigDecimal englishTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.PE_total
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    @ExcelProperty("体育总分")
    private BigDecimal peTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.math_average
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    @ExcelProperty("数学平均分")
    private BigDecimal mathAverage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.Java_average
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    @ExcelProperty("Java平均分")
    private BigDecimal javaAverage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.english_average
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    @ExcelProperty("英语平均分")
    private BigDecimal englishAverage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.PE_average
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    @ExcelProperty("体育平均分")
    private BigDecimal peAverage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.total
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    @ExcelProperty("总分")
    private BigDecimal total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.total_average
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    @ExcelProperty("总分平均分")
    private BigDecimal totalAverage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.math_total
     *
     * @return the value of grade.math_total
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    public BigDecimal getMathTotal() {
        return mathTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.math_total
     *
     * @param mathTotal the value for grade.math_total
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    public void setMathTotal(BigDecimal mathTotal) {
        this.mathTotal = mathTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.Java_total
     *
     * @return the value of grade.Java_total
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    public BigDecimal getJavaTotal() {
        return javaTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.Java_total
     *
     * @param javaTotal the value for grade.Java_total
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    public void setJavaTotal(BigDecimal javaTotal) {
        this.javaTotal = javaTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.english_total
     *
     * @return the value of grade.english_total
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    public BigDecimal getEnglishTotal() {
        return englishTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.english_total
     *
     * @param englishTotal the value for grade.english_total
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    public void setEnglishTotal(BigDecimal englishTotal) {
        this.englishTotal = englishTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.PE_total
     *
     * @return the value of grade.PE_total
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    public BigDecimal getPeTotal() {
        return peTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.PE_total
     *
     * @param peTotal the value for grade.PE_total
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    public void setPeTotal(BigDecimal peTotal) {
        this.peTotal = peTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.math_average
     *
     * @return the value of grade.math_average
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    public BigDecimal getMathAverage() {
        return mathAverage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.math_average
     *
     * @param mathAverage the value for grade.math_average
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    public void setMathAverage(BigDecimal mathAverage) {
        this.mathAverage = mathAverage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.Java_average
     *
     * @return the value of grade.Java_average
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    public BigDecimal getJavaAverage() {
        return javaAverage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.Java_average
     *
     * @param javaAverage the value for grade.Java_average
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    public void setJavaAverage(BigDecimal javaAverage) {
        this.javaAverage = javaAverage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.english_average
     *
     * @return the value of grade.english_average
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    public BigDecimal getEnglishAverage() {
        return englishAverage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.english_average
     *
     * @param englishAverage the value for grade.english_average
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    public void setEnglishAverage(BigDecimal englishAverage) {
        this.englishAverage = englishAverage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.PE_average
     *
     * @return the value of grade.PE_average
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    public BigDecimal getPeAverage() {
        return peAverage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.PE_average
     *
     * @param peAverage the value for grade.PE_average
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    public void setPeAverage(BigDecimal peAverage) {
        this.peAverage = peAverage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.total
     *
     * @return the value of grade.total
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    public BigDecimal getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.total
     *
     * @param total the value for grade.total
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.total_average
     *
     * @return the value of grade.total_average
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    public BigDecimal getTotalAverage() {
        return totalAverage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.total_average
     *
     * @param totalAverage the value for grade.total_average
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    public void setTotalAverage(BigDecimal totalAverage) {
        this.totalAverage = totalAverage;
    }
}