package org.joey.pojo;

import java.math.BigDecimal;

public class StudentGrade {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_grade.num
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_grade.name
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_grade.math
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    private BigDecimal math;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_grade.Java
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    private BigDecimal java;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_grade.English
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    private BigDecimal english;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_grade.PE
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    private BigDecimal pe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_grade.total
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    private BigDecimal total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_grade.average
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    private BigDecimal average;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_grade.num
     *
     * @return the value of student_grade.num
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_grade.num
     *
     * @param num the value for student_grade.num
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_grade.name
     *
     * @return the value of student_grade.name
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_grade.name
     *
     * @param name the value for student_grade.name
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_grade.math
     *
     * @return the value of student_grade.math
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    public BigDecimal getMath() {
        return math;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_grade.math
     *
     * @param math the value for student_grade.math
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    public void setMath(BigDecimal math) {
        this.math = math;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_grade.Java
     *
     * @return the value of student_grade.Java
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    public BigDecimal getJava() {
        return java;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_grade.Java
     *
     * @param java the value for student_grade.Java
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    public void setJava(BigDecimal java) {
        this.java = java;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_grade.English
     *
     * @return the value of student_grade.English
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    public BigDecimal getEnglish() {
        return english;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_grade.English
     *
     * @param english the value for student_grade.English
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    public void setEnglish(BigDecimal english) {
        this.english = english;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_grade.PE
     *
     * @return the value of student_grade.PE
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    public BigDecimal getPe() {
        return pe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_grade.PE
     *
     * @param pe the value for student_grade.PE
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    public void setPe(BigDecimal pe) {
        this.pe = pe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_grade.total
     *
     * @return the value of student_grade.total
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    public BigDecimal getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_grade.total
     *
     * @param total the value for student_grade.total
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_grade.average
     *
     * @return the value of student_grade.average
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    public BigDecimal getAverage() {
        return average;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_grade.average
     *
     * @param average the value for student_grade.average
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    public void setAverage(BigDecimal average) {
        this.average = average;
    }
}