package org.joey.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.joey.pojo.Grade;
import org.joey.pojo.GradeExample;
import org.springframework.stereotype.Component;

@Component
public interface GradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    long countByExample(GradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    int deleteByExample(GradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    int insert(Grade row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    int insertSelective(Grade row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    List<Grade> selectByExample(GradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    int updateByExampleSelective(@Param("row") Grade row, @Param("example") GradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    int updateByExample(@Param("row") Grade row, @Param("example") GradeExample example);
}