package org.joey.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.joey.pojo.StudentGrade;
import org.joey.pojo.StudentGradeExample;
import org.springframework.stereotype.Component;

@Component
public interface StudentGradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_grade
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    long countByExample(StudentGradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_grade
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    int deleteByExample(StudentGradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_grade
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    int deleteByPrimaryKey(Integer num);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_grade
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    int insert(StudentGrade row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_grade
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    int insertSelective(StudentGrade row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_grade
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    List<StudentGrade> selectByExample(StudentGradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_grade
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    StudentGrade selectByPrimaryKey(Integer num);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_grade
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    int updateByExampleSelective(@Param("row") StudentGrade row, @Param("example") StudentGradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_grade
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    int updateByExample(@Param("row") StudentGrade row, @Param("example") StudentGradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_grade
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    int updateByPrimaryKeySelective(StudentGrade row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_grade
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    int updateByPrimaryKey(StudentGrade row);
}