package org.joey.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.joey.pojo.Student;
import org.joey.pojo.StudentExample;
import org.springframework.stereotype.Component;

@Component
public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    long countByExample(StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    int deleteByExample(StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    int deleteByPrimaryKey(Integer num);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    int insert(Student row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    int insertSelective(Student row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    List<Student> selectByExample(StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    Student selectByPrimaryKey(Integer num);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    int updateByExampleSelective(@Param("row") Student row, @Param("example") StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    int updateByExample(@Param("row") Student row, @Param("example") StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    int updateByPrimaryKeySelective(Student row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Sep 07 10:28:19 CST 2022
     */
    int updateByPrimaryKey(Student row);
}